apiVersion: v1
kind: Service
metadata:
  name: ish-api
  namespace: ish-automation
  labels:
    app: ish-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: ish-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: v1
kind: Service
metadata:
  name: ish-web
  namespace: ish-automation
  labels:
    app: ish-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: ish-web
---
apiVersion: v1
kind: Service
metadata:
  name: ish-pwa
  namespace: ish-automation
  labels:
    app: ish-pwa
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: ish-pwa
---
apiVersion: v1
kind: Service
metadata:
  name: ish-redis
  namespace: ish-automation
  labels:
    app: ish-redis
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: ish-redis
---
apiVersion: v1
kind: Service
metadata:
  name: ish-postgres
  namespace: ish-automation
  labels:
    app: ish-postgres
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: ish-postgres
